package sbs.yanji.daoyou;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;

/** Native Android Views only. Every authoritative value comes from the game API. */
public final class MainActivity extends Activity {
    private static final int INK=0xff29372f, GREEN=0xff23604f, PAPER=0xfff5f2e9, WHITE=0xfffffdf7, MUTED=0xff738075;
    private GameApi api; private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private final Handler main=new Handler(Looper.getMainLooper());
    private LinearLayout root,body,nav; private TextView status; private ProgressBar spinner;
    private JSONObject resources=new JSONObject(); private String page="角色", inventoryType="artifacts"; private int inventoryPage=1;
    private boolean busy=false, foreground=false, signedIn=false; private int generation=0;
    private int realmPolls=0; private final Runnable realmPoll=()->{if(foreground&&page.equals("天灵秘境")&&!busy)realm();};
    private long lastSync=0; private final Runnable realtimeRefresh=()-> { if(foreground&&signedIn&&!busy&&System.currentTimeMillis()-lastSync>1500)refresh(); };
    interface Work { JSONObject run() throws Exception; } interface Done { void accept(JSONObject value) throws Exception; }
    @Override public void onCreate(Bundle b) { super.onCreate(b); api=new GameApi(this); shell(); loadSession(); }
    @Override protected void onResume(){super.onResume();foreground=true;if(signedIn){if(foreground)api.startRealtime(()->main.post(realtimeRefresh)); if(!busy)refresh();}}
    @Override protected void onPause(){foreground=false;main.removeCallbacks(realmPoll);api.stopRealtime();super.onPause();}
    @Override protected void onDestroy(){generation++;api.close();worker.shutdownNow();main.removeCallbacksAndMessages(null);super.onDestroy();}
    @Override public void onBackPressed(){ if(!page.equals("角色")&&signedIn){page="角色";refresh();}else new AlertDialog.Builder(this).setMessage("退出游戏？进度已保存在服务器。").setNegativeButton("继续游玩",null).setPositiveButton("退出",(d,w)->finish()).show(); }
    private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private GradientDrawable bg(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(16));d.setStroke(dp(1),0xffdedfd4);return d;}
    private TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(5),0,dp(5));t.setLineSpacing(dp(3),1);return t;}
    private void addText(LinearLayout p,String s,int size,int color){p.addView(text(s,size,color));}
    private LinearLayout vertical(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private LinearLayout card(String title){LinearLayout c=vertical();c.setPadding(dp(16),dp(12),dp(16),dp(14));c.setBackground(bg(WHITE));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(14);body.addView(c,lp);if(!title.isEmpty()){TextView t=text(title,20,INK);t.setTypeface(null,Typeface.BOLD);c.addView(t);}return c;}
    private Button button(LinearLayout p,String label,boolean primary,Runnable action){Button b=new Button(this);b.setText(label);b.setTextSize(16);b.setAllCaps(false);b.setTextColor(primary?Color.WHITE:GREEN);b.setBackground(bg(primary?GREEN:PAPER));b.setMinHeight(dp(50));b.setPadding(dp(12),dp(8),dp(12),dp(8));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(9);p.addView(b,lp);b.setOnClickListener(v->{if(!busy)action.run();});return b;}
    private void shell(){root=vertical();root.setBackgroundColor(PAPER);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop(),i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());return i;});setContentView(root);
        LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(20),dp(10),dp(12),dp(8));TextView title=text("万界道友•衍极界",21,INK);title.setTypeface(Typeface.SERIF,Typeface.BOLD);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView sync=text("刷新",15,GREEN);sync.setGravity(Gravity.CENTER);sync.setMinHeight(dp(48));sync.setMinWidth(dp(48));sync.setOnClickListener(v->{if(!busy&&signedIn)refresh();});header.addView(sync);root.addView(header);
        spinner=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);spinner.setIndeterminate(true);spinner.setVisibility(View.GONE);root.addView(spinner,new LinearLayout.LayoutParams(-1,dp(3)));
        status=text("正在连接服务器…",12,MUTED);status.setPadding(dp(20),0,dp(20),dp(5));root.addView(status);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);body=vertical();body.setPadding(dp(16),dp(10),dp(16),dp(12));scroll.addView(body,new android.widget.FrameLayout.LayoutParams(Math.min(getResources().getDisplayMetrics().widthPixels,dp(720)),-2,Gravity.CENTER_HORIZONTAL));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setBackgroundColor(WHITE);root.addView(nav);}
    private void navigation(){nav.removeAllViews();if(!signedIn)return;for(String s:new String[]{"角色","储物袋","洞府","传音","更多"}){TextView t=text(s,14,page.equals(s)?GREEN:MUTED);t.setGravity(Gravity.CENTER);t.setMinHeight(dp(60));t.setTypeface(null,page.equals(s)?Typeface.BOLD:Typeface.NORMAL);nav.addView(t,new LinearLayout.LayoutParams(0,-2,1));t.setOnClickListener(v->{if(!busy){page=s;refresh();}});}}
    private void request(String label,Work work,Done done){if(busy)return;busy=true;spinner.setVisibility(View.VISIBLE);status.setText(label);final int token=generation;
        worker.execute(()->{try{JSONObject r=work.run();main.post(()->{if(isDestroyed()||token!=generation)return;busy=false;spinner.setVisibility(View.GONE);try{done.accept(r);status.setText("已同步 · 与网页端共用进度");lastSync=System.currentTimeMillis();}catch(Exception e){showError("服务器数据暂时无法显示，请刷新重试。");}});}catch(Exception e){main.post(()->{if(isDestroyed()||token!=generation)return;busy=false;spinner.setVisibility(View.GONE);if(e instanceof GameApi.ApiException && ((GameApi.ApiException)e).statusCode==401){api.clearSession();resources=new JSONObject();loginScreen();}String message=e.getMessage();showError(message==null?"连接失败，请检查网络后重试。":message);});}});}
    private void showError(String message){status.setText("同步未完成 · 请重试");new AlertDialog.Builder(this).setTitle("操作未完成").setMessage(message).setPositiveButton("知道了",null).show();if(body.getChildCount()==0){LinearLayout c=card("暂时无法连接");addText(c,"请检查网络，再点击重试。",16,MUTED);button(c,"重试",true,()->{if(signedIn)refresh();else loadSession();});}}
    private static JSONObject obj(JSONObject o,String key){JSONObject v=o.optJSONObject(key);return v==null?new JSONObject():v;}
    private static JSONArray arr(JSONObject o,String key){JSONArray a=o.optJSONArray(key);return a==null?new JSONArray():a;}
    private JSONObject data(String key){return obj(obj(resources,key),"data");}
    private JSONObject payload(JSONObject r){return r.has("data")?obj(r,"data"):r;}
    private void loadSession(){request("检查登录状态…",()->api.get("/api/auth/get-session"),r->{if(r.has("user")&&!r.isNull("user")){signedIn=true;navigation();main.post(this::refresh);if(foreground)api.startRealtime(()->main.post(realtimeRefresh));}else loginScreen();});}
    private EditText input(LinearLayout c,String hint,int type){EditText e=new EditText(this);e.setTextSize(16);e.setTextColor(INK);e.setHint(hint);e.setInputType(type);e.setSingleLine(true);e.setMinHeight(dp(54));c.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
    private void loginScreen(){signedIn=false;navigation();body.removeAllViews();status.setText("使用已有游戏账号登录");InkLandscape art=new InkLandscape(this);body.addView(art,new LinearLayout.LayoutParams(-1,dp(145)));LinearLayout c=card("重返仙途");addText(c,"账号、角色与网页端互通",15,MUTED);EditText email=input(c,"邮箱",33),password=input(c,"密码",129);password.setSaveEnabled(false);button(c,"登录",true,()->{String mail=email.getText().toString().trim(),pw=password.getText().toString();if(mail.isEmpty()||pw.isEmpty()){showError("请填写邮箱和密码");return;}request("正在安全验证，请稍候…",()->api.login(mail,pw),r->{password.setText("");signedIn=true;navigation();main.post(this::refresh);if(foreground)api.startRealtime(()->main.post(realtimeRefresh));});});
        LinearLayout otp=card("邮箱验证码登录");EditText code=input(otp,"6 位验证码",2),name=input(otp,"昵称（首次注册填写）",1);button(otp,"发送验证码",false,()->request("正在安全验证并发送验证码…",()->api.sendOtp(email.getText().toString().trim()),r->Toast.makeText(this,"验证码已发送，请查看邮箱",Toast.LENGTH_LONG).show()));button(otp,"验证并进入",false,()->request("验证邮箱…",()->api.loginOtp(email.getText().toString().trim(),code.getText().toString().trim(),name.getText().toString().trim()),r->{signedIn=true;navigation();main.post(this::refresh);if(foreground)api.startRealtime(()->main.post(realtimeRefresh));}));}
    private void refresh(){navigation();switch(page){case "储物袋":inventory();break;case "天灵秘境":realm();break;case "传音":mail();break;case "更多":more();break;case "天骄榜":rankings();break;default:request("同步角色状态…",()->{JSONObject session=api.get("/api/player/resources?keys=session");JSONObject sd=obj(obj(obj(payload(session),"resources"),"session"),"data");if(obj(sd,"activeCultivator").length()==0)return session;return api.get("/api/player/resources?keys=session,profile,condition,progress,currency,loadout");},r->{resources=obj(payload(r),"resources");if(obj(data("session"),"activeCultivator").length()==0){body.removeAllViews();LinearLayout c=card("尚无在世角色");addText(c,"此原生首版暂未接入创角流程。请先在网页端创建角色，再返回刷新。",16,MUTED);return;}if(page.equals("洞府"))retreatScreen();else if(page.equals("功法"))loadout();else home();});}}
    private void home(){page="角色";navigation();body.removeAllViews();JSONObject p=obj(data("profile"),"cultivator"),progress=data("progress"),currency=data("currency");LinearLayout who=card(p.optString("name","道友"));addText(who,p.optString("realm")+" · "+p.optString("realm_stage"),17,GREEN);addText(who,"寿元  "+p.optString("age","—")+" / "+p.optString("lifespan","—"),14,MUTED);
        JSONObject cond=obj(data("condition"),"resources");addText(who,"气血  "+resourceValue(obj(cond,"hp"))+"     法力  "+resourceValue(obj(cond,"mp")),16,INK);addText(who,"天地灵气  "+currency.optString("qi","—")+"     灵石  "+currency.optString("spiritStones","—"),16,INK);
        LinearLayout cultivation=card("修行进度");cultivation.addView(new InkLandscape(this),new LinearLayout.LayoutParams(-1,dp(130)));addText(cultivation,"修为  "+progress.optString("cultivation_exp","—")+" / "+progress.optString("exp_cap","—"),17,INK);ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(1000);bar.setProgress((int)Math.min(1000,1000*progress.optDouble("cultivation_exp",0)/Math.max(1,progress.optDouble("exp_cap",1))));cultivation.addView(bar);button(cultivation,"闭关修炼",true,()->{page="洞府";retreatScreen();});
        LinearLayout arts=card("修行与造化");button(arts,"功法与灵根",false,this::loadout);button(arts,"天灵秘境  ›",false,()->{page="天灵秘境";realm();});button(arts,"储物袋  ›",false,()->{page="储物袋";inventory();});}
    private String resourceValue(JSONObject o){return o.has("max")?o.optString("current","待同步")+" / "+o.optString("max"):o.optString("current","待同步");}
    private void loadout(){page="功法";body.removeAllViews();LinearLayout c=card("所修功法");JSONObject l=data("loadout");for(String k:new String[]{"skills","cultivations","artifacts"}){JSONArray a=arr(l,k);for(int i=0;i<a.length();i++){JSONObject item=a.optJSONObject(i);if(item!=null)button(c,item.optString("name","修行典籍"),false,()->detail(item,null));}}LinearLayout roots=card("灵根与属性");JSONObject p=obj(data("profile"),"cultivator");addText(roots,"灵根",17,GREEN);JSONArray rootList=arr(p,"spiritual_roots");for(int ri=0;ri<rootList.length();ri++){JSONObject sr=objAt(rootList,ri);addText(roots,sr.optString("element",sr.optString("name","灵根"))+"  强度 "+sr.optString("strength","—"),15,INK);}addText(roots,"基础属性",17,GREEN);display(roots,p.opt("attributes"));button(roots,"返回角色",false,this::home);}
    private void retreatScreen(){body.removeAllViews();LinearLayout c=card("洞府 · 闭关");c.addView(new InkLandscape(this),new LinearLayout.LayoutParams(-1,dp(145)));addText(c,"闭关将按游戏规则消耗寿元和天地灵气。突破成功率与消耗由服务器判定。",16,MUTED);EditText years=input(c,"闭关年数",2);years.setText("1");button(c,"闭关修炼",true,()->{try{int n=Integer.parseInt(years.getText().toString());if(n<1||n>100)throw new NumberFormatException();confirm("闭关 "+n+" 年？",()->doRetreat("cultivate",n));}catch(NumberFormatException e){showError("请输入 1～100 年，服务器会进一步校验境界限制。");}});button(c,"尝试突破",false,()->confirm("按当前境界规则尝试突破？",()->doRetreat("breakthrough",0)));button(c,"天灵秘境",false,()->{page="天灵秘境";realm();});}
    private void doRetreat(String action,int years){request("正在闭关，请勿重复提交…",()->api.retreat(action,years),r->{JSONObject result=obj(r,"data"),summary=obj(result,"summary");String message=action.equals("cultivate")?"获得修为 "+summary.optString("exp_gained","—")+"，感悟增加 "+summary.optString("insight_gained","—"):summary.optBoolean("success")?"突破成功，当前境界："+summary.optString("toRealm")+"·"+summary.optString("toStage"):"此次突破未成功。请查看最新状态，再作准备。";new AlertDialog.Builder(this).setTitle("修行结果").setMessage(message).setPositiveButton("收下感悟",null).show();main.post(this::refresh);});}
    private void confirm(String message,Runnable yes){new AlertDialog.Builder(this).setTitle("确认操作").setMessage(message).setNegativeButton("取消",null).setPositiveButton("确认",(d,w)->yes.run()).show();}
    private void inventory(){request("读取储物袋…",()->api.get("/api/cultivator/inventory?type="+inventoryType+"&page="+inventoryPage+"&pageSize=20"),r->{body.removeAllViews();navigation();LinearLayout filters=card("储物袋");String[] keys={"artifacts","consumables","materials"},labels={"法宝","丹药","材料"};LinearLayout row=new LinearLayout(this);filters.addView(row);for(int i=0;i<keys.length;i++){final String key=keys[i];TextView t=text(labels[i],16,key.equals(inventoryType)?GREEN:MUTED);t.setMinHeight(dp(48));t.setGravity(Gravity.CENTER);row.addView(t,new LinearLayout.LayoutParams(0,-2,1));t.setOnClickListener(v->{if(!busy){inventoryType=key;inventoryPage=1;inventory();}});}JSONObject d=payload(r);JSONArray items=arr(d,"items");if(items.length()==0)addText(filters,"这里还没有物品。",16,MUTED);for(int i=0;i<items.length();i++){JSONObject item=items.optJSONObject(i);if(item==null)continue;LinearLayout c=card(item.optString("name","物品"));addText(c,item.optString("quality",item.optString("rank",""))+"  "+item.optString("element","")+"  ×"+item.optString("quantity","1"),14,GREEN);addText(c,item.optString("description",""),14,MUTED);button(c,"查看详情",false,()->detail(item,inventoryType));}JSONObject pagination=obj(d,"pagination");LinearLayout pages=card("");addText(pages,"第 "+inventoryPage+" 页 · 共 "+pagination.optInt("total",0)+" 件",14,MUTED);if(inventoryPage>1)button(pages,"上一页",false,()->{inventoryPage--;inventory();});if(pagination.optBoolean("hasMore"))button(pages,"下一页",false,()->{inventoryPage++;inventory();});});}
    private void detail(JSONObject item,String type){LinearLayout c=vertical();c.setPadding(dp(22),dp(12),dp(22),dp(18));addText(c,item.optString("name","物品"),24,INK);addText(c,item.optString("quality",item.optString("rank","")),16,GREEN);addText(c,item.optString("description","暂无描述"),16,INK);if(item.has("slot"))addText(c,"装备位置  "+item.optString("slot"),15,MUTED);AlertDialog dialog=new AlertDialog.Builder(this).setView(c).setNegativeButton("关闭",null).create();if("artifacts".equals(type))button(c,item.optBoolean("isEquipped")?"切换装备状态":"装备",true,()->{dialog.dismiss();confirm("切换此法宝的装备状态？",()->mutate("/api/cultivator/equip",json("artifactId",item.optString("id")),this::inventory));});if("consumables".equals(type))button(c,"使用丹药",true,()->{dialog.dismiss();confirm("使用一份「"+item.optString("name")+"」？",()->mutate("/api/cultivator/consume",json("consumableId",item.optString("id")),this::inventory));});dialog.show();}
    private void mutate(String path,JSONObject value,Runnable next){request("正在提交，请勿重复操作…",()->api.post(path,value),r->{Toast.makeText(this,"操作完成",Toast.LENGTH_SHORT).show();main.post(next);});}
    private static JSONObject json(String key,Object value){JSONObject o=new JSONObject();try{o.put(key,value);}catch(JSONException ignored){}return o;}
    private static String recoveryLabel(String a){switch(a){case "retry":return "重试当前步骤";case "retry_continue":return "重试战后推进";case "retry_settle":return "重试奖励结算";case "safe_retreat":return "安全撤离并结算";case "force_quit":return "强制结束探索";default:return "恢复探索";}}
    private static String riskLabel(String r){return r.equals("high")?"较高":r.equals("medium")?"中等":"较低";}
    private void realm(){request("读取秘境进度…",()->{JSONObject result=new JSONObject();result.put("config",api.get("/api/secret-realms"));result.put("run",api.get("/api/dungeon/state"));return result;},r->{body.removeAllViews();LinearLayout hero=card("天灵秘境");hero.addView(new InkLandscape(this),new LinearLayout.LayoutParams(-1,dp(150)));JSONArray all=arr(r.getJSONObject("config"),"realms");JSONObject config=new JSONObject();for(int i=0;i<all.length();i++){JSONObject a=all.optJSONObject(i);if(a!=null&&a.optString("name").contains("天灵")){config=a;break;}}addText(hero,config.optString("description","击败守卫与首领，领取本期奖励。"),16,MUTED);LinearLayout rewards=card("通关奖励");addText(rewards,config.optString("rewardDescription","以服务器本期配置为准"),16,INK);JSONObject state=obj(r.getJSONObject("run"),"state");if(state.length()==0||state.optBoolean("isFinished")){if(state.length()>0){LinearLayout done=card("上次探索已结束");display(done,state.opt("settlement"));}final boolean enabled=config.optBoolean("enabled",false)&&config.optBoolean("rewardsAvailable",true);addText(rewards,"今日已进入 "+config.optInt("usedToday",0)+" / "+config.optInt("dailyLimit",0)+" 次",14,MUTED);if(enabled)button(rewards,"进入秘境",true,()->confirm("消耗一次今日进入次数，进入天灵秘境？",()->mutate("/api/dungeon/start",json("mapNodeId","SAT_TIANLING_01"),this::realm)));else addText(rewards,"秘境暂未开放",16,MUTED);return;}
        LinearLayout c=card("挑战进度");addText(c,"第 "+state.optInt("currentRound")+" / "+state.optInt("maxRounds")+" 轮",18,GREEN);addText(c,state.optString("theme",""),16,INK);JSONArray history=arr(state,"history");if(history.length()>0)addText(c,objAt(history,history.length()-1).optString("scene",""),16,INK);if(!state.optString("mapNodeId").equals("SAT_TIANLING_01")){addText(c,"你正在其他探索中，请先完成当前探索。",16,MUTED);return;}String battle=state.optString("activeBattleId","");if("WAITING_BATTLE".equals(state.optString("status"))&&!battle.isEmpty()&&!battle.equals("null")){button(c,"迎战",true,()->{JSONObject b=json("battleId",battle);try{b.put("requestId",UUID.randomUUID().toString());}catch(JSONException ignored){}request("正在与对手交锋…",()->api.post("/api/dungeon/battle/execute/v5",b),answer->{JSONObject battleResult=obj(payload(answer),"battleResult"),outcome=obj(battleResult,"outcome");if(outcome.has("winner")){boolean win=obj(outcome,"winner").optString("id").equals(obj(obj(battleResult,"participants"),"player").optString("id"));new AlertDialog.Builder(this).setTitle(win?"战斗获胜":"战斗结束").setMessage("胜者："+obj(outcome,"winner").optString("name")+"\n交锋回合："+outcome.optString("turns")).setPositiveButton("继续",null).show();}main.post(this::realm);});});}
        JSONArray options="EXPLORING".equals(state.optString("status"))?arr(state,"currentOptions"):new JSONArray();for(int i=0;i<options.length();i++){JSONObject choice=options.optJSONObject(i);if(choice==null)continue;final int id=choice.optInt("id",-1);if(id<0)continue;addText(c,"风险："+riskLabel(choice.optString("risk_level")),13,MUTED);JSONArray costs=choice.optJSONArray("costPreview");if(costs==null)costs=arr(choice,"costs");for(int ci=0;ci<costs.length();ci++){JSONObject cost=objAt(costs,ci);addText(c,"消耗："+cost.optString("name",cost.optString("desc","资源"))+" "+cost.optString("value"),14,MUTED);}button(c,choice.optString("text",choice.optString("label","继续探索")),false,()->confirm("选择「"+choice.optString("text","继续探索")+"」？消耗与结果按服务器规则结算。",()->{JSONObject b=json("choiceId",id);try{b.put("actionId",UUID.randomUUID().toString());}catch(JSONException ignored){}mutate("/api/dungeon/action",b,this::realm);}));}String st=state.optString("status");if(st.equals("LOOTING"))button(c,"继续探索",true,()->mutate("/api/dungeon/looting/continue",new JSONObject(),this::realm));if(st.equals("GENERATING_NEXT")||st.equals("SETTLING")||st.equals("IN_BATTLE")){addText(c,"服务器正在处理，请稍后刷新。",16,MUTED);main.removeCallbacks(realmPoll);if(realmPolls++<20)main.postDelayed(realmPoll,3000);}else realmPolls=0;JSONArray actions=arr(state,"recoverableActions");for(int i=0;i<actions.length();i++){String a=actions.optString(i);button(c,recoveryLabel(a),false,()->confirm(a.equals("force_quit")||a.equals("safe_retreat")?"确认退出当前探索？收益以服务器结算为准。":"确认恢复当前探索？",()->mutate("/api/dungeon/recover",json("action",a),this::realm)));}button(c,"刷新进度",false,this::realm);button(c,"退出探索",false,()->confirm("确定退出当前探索？奖励按服务器规则结算。",()->mutate("/api/dungeon/quit",new JSONObject(),this::realm)));});}
    private int mailPage=1;
    private void mail(){request("读取游戏邮件…",()->api.get("/api/cultivator/mail?page="+mailPage+"&pageSize=20"),r->{body.removeAllViews();LinearLayout header=card("游戏邮件");addText(header,"查看通知与领取附件奖励",15,MUTED);JSONArray mails=arr(r,"mails");if(mails.length()==0)addText(header,"暂无邮件",16,MUTED);for(int i=0;i<mails.length();i++){JSONObject item=objAt(mails,i);LinearLayout c=card(item.optString("title","游戏邮件"));addText(c,item.optString("content"),16,INK);JSONArray attachments=arr(item,"attachments");for(int j=0;j<attachments.length();j++){JSONObject a=objAt(attachments,j);addText(c,a.optString("name","奖励")+" ×"+a.optString("quantity","1"),15,GREEN);}if(attachments.length()>0&&!item.optBoolean("isClaimed"))button(c,"领取附件",true,()->mutate("/api/cultivator/mail/claim",json("mailId",item.optString("id")),this::mail));else if(item.optBoolean("isClaimed"))addText(c,"附件已领取",14,MUTED);if(!item.optBoolean("isRead"))button(c,"标为已读",false,()->mutate("/api/cultivator/mail/read",json("mailId",item.optString("id")),this::mail));}LinearLayout pager=card("");if(mailPage>1)button(pager,"上一页",false,()->{mailPage--;mail();});if(obj(r,"pagination").optBoolean("hasMore"))button(pager,"下一页",false,()->{mailPage++;mail();});});}
    private static JSONObject objAt(JSONArray a,int i){JSONObject o=a.optJSONObject(i);return o==null?new JSONObject():o;}

    private void rankings(){page="天骄榜";request("读取天骄榜…",()->api.get("/api/rankings?realm="+java.net.URLEncoder.encode(obj(data("profile"),"cultivator").optString("realm","炼气"),"UTF-8")),r->{body.removeAllViews();LinearLayout top=card("天骄榜");addText(top,r.optString("realm",""),16,GREEN);JSONArray list=arr(r,"data");if(list.length()==0)addText(top,"本境界暂未有人登榜",16,MUTED);for(int i=0;i<list.length();i++){JSONObject item=objAt(list,i);LinearLayout c=card("第 "+item.optString("rank")+" 名 · "+item.optString("name"));addText(c,item.optString("realm")+" · "+item.optString("realm_stage"),16,GREEN);addText(c,item.optString("title",""),14,MUTED);}});}
    private void more(){body.removeAllViews();navigation();LinearLayout c=card("设置");addText(c,"万界道友•衍极界\n原生安卓客户端 0.1.0\n服务器：daoyou.yanji.sbs",16,INK);button(c,"天骄榜",false,this::rankings);button(c,"同步角色数据",false,()->{page="角色";refresh();});button(c,"退出账号",false,()->confirm("退出此设备上的账号？",()->request("退出账号…",()->{api.logout();return new JSONObject();},r->{api.stopRealtime();resources=new JSONObject();loginScreen();})));}
    private static final Map<String,String> LABELS=new HashMap<>();
    static {String[] keys={"vitality","strength","spirit","endurance","speed","willpower","name","element","strengthValue","value"};String[] names={"体魄","力道","灵力","根骨","身法","神识","名称","五行","强度","数值"};for(int i=0;i<keys.length;i++)LABELS.put(keys[i],names[i]);}
    private void display(LinearLayout c,Object value){if(value instanceof JSONArray){JSONArray a=(JSONArray)value;for(int i=0;i<a.length();i++)display(c,a.opt(i));}else if(value instanceof JSONObject){JSONObject o=(JSONObject)value;Iterator<String> it=o.keys();while(it.hasNext()){String k=it.next();Object v=o.opt(k);if(v instanceof JSONArray||v instanceof JSONObject)continue;if(k.equals("id")||k.endsWith("Id"))continue;addText(c,LABELS.getOrDefault(k,k)+"  "+String.valueOf(v),15,INK);}}else if(value!=null&&value!=JSONObject.NULL)addText(c,String.valueOf(value),15,INK);}
}
